us_state_TZ = {'Alabama': 'CTC',

 'Alaska': 'Alaskan time zone',
 'American Samoa': 'ETC',
 'Arizona': 'MTC',
 'Arkansas': 'CTC',
 'California': 'PTC',
 'Colorado': 'MTC',
 'Connecticut': 'ETC',
 'Delaware': 'ETC',
 'District of Columbia': 'ETC',
 'Florida': 'ETC',
 'Georgia': 'ETC',
 'Guam': 'ETC',
 'Hawaii': 'Hawaian time zone',
 'Idaho': 'MTC',
 'Illinois': 'CTC',
 'Indiana': 'ETC',
 'Iowa': 'CTC',
 'Kansas': 'CTC',
 'Kentucky': 'CTC',
 'Louisiana': 'CTC',
 'Maine': 'ETC',
 'Maryland': 'ETC',
 'Massachusetts': 'ETC',
 'Michigan': 'ETC',
 'Minnesota': 'CTC',
 'Mississippi': 'CTC',
 'Missouri': 'CTC',
 'Montana': 'MTC',
 'Nebraska': 'CTC',
 'Nevada': 'PTC',
 'New Hampshire': 'ETC',
 'New Jersey': 'ETC',
 'New Mexico': 'MTC',
 'New York': 'ETC',
 'North Carolina': 'ETC',
 'North Dakota': 'CTC',
 'Northern Mariana Islands': 'ETC',
 'Ohio': 'ETC',
 'Oklahoma': 'CTC',
 'Oregon': 'PTC',
 'Pennsylvania': 'ETC',
 'Puerto Rico': 'ETC',
 'Rhode Island': 'ETC',
 'South Carolina': 'ETC',
 'South Dakota': 'CTC',
 'Tennessee': 'CTC',
 'Texas': 'CTC',
 'Utah': 'MTC',
 'Vermont': 'ETC',
 'Virgin Islands': 'ETC',
 'Virginia': 'ETC',
 'Washington': 'PTC',
 'West Virginia': 'ETC',
 'Wisconsin': 'CTC',
 'Wyoming': 'MTC'
 }
us_time = {'Alabama': -6,
 'Alaska': -9,
 'American Samoa': -5,
 'Arizona': -7,
 'Arkansas': -6,
 'California': -8,
 'Colorado': -7,
 'Connecticut': -5,
 'Delaware': -5,
 'District of Columbia': -5,
 'Florida': -5,
 'Georgia': -5,
 'Guam': -5,
 'Hawaii': -10,
 'Idaho': -7,
 'Illinois': -6,
 'Indiana': -5,
 'Iowa': -6,
 'Kansas': -6,
 'Kentucky': -6,
 'Louisiana': -6,
 'Maine': -5,
 'Maryland': -5,
 'Massachusetts': -5,
 'Michigan': -5,
 'Minnesota': -6,
 'Mississippi': -6,
 'Missouri': -6,
 'Montana': -7,
 'Nebraska': -6,
 'Nevada': -8,
 'New Hampshire': -5,
 'New Jersey': -5,
 'New Mexico': -7,
 'New York': -5,
 'North Carolina': -5,
 'North Dakota': -6,
 'Northern Mariana Islands': -5,
 'Ohio': -5,
 'Oklahoma': -6,
 'Oregon': -8,
 'Pennsylvania': -5,
 'Puerto Rico': -5,
 'Rhode Island': -5,
 'South Carolina': -5,
 'South Dakota': -6,
 'Tennessee': -6,
 'Texas': -6,
 'Utah': -7,
 'Vermont': -5,
 'Virgin Islands': -5,
 'Virginia': -5,
 'Washington': -8,
 'West Virginia': -5,
 'Wisconsin': -6,
 'Wyoming': -7}
 